grafana:
  image: grafana/grafana:latest
  replicas: 1
  service:
    type: ClusterIP
    port: 3000

prometheus:
  image: prom/prometheus:main
  replicas: 1
  service:
    type: ClusterIP
    port: 9090
  config:
    scrape_interval: "15s"
    evaluation_interval: "15s"
    targets:
      - "blackbox-exporter:9115"

blackboxExporter:
  image: prom/blackbox-exporter:latest
  replicas: 1
  service:
    type: ClusterIP
    port: 9115