apiVersion: v1
kind: Service
metadata:
  name: blackbox-exporter
spec:
  type: {{ .Values.blackboxExporter.service.type }}
  ports:
    - port: {{ .Values.blackboxExporter.service.port }}
      targetPort: 9115
  selector:
    app: blackbox-exporter